apiVersion: apps/v1
kind: Deployment
metadata:
  name: ikev2-vpn
spec:
  selector:
    matchLabels:
      k8s-app: ikev2-vpn
  template:
    metadata:
      name: ikev2-vpn
      labels:
        k8s-app: ikev2-vpn
    spec:
      restartPolicy: Always
      containers:
        - name: ikev2-vpn
          image: hwdsl2/ipsec-vpn-server
          securityContext:
              privileged: true
          volumeMounts:
            - name: vpn-data
              mountPath: /etc/ipsec.d
              readOnly: false
      volumes:
        - name: vpn-data
          ikev2-vpn-data:

---

apiVersion: v1
kind: Service
metadata:
  name: ikev2-vpn
spec:
  type: LoadBalancer
  selector:
    k8s-app: ikev2-vpn
  ports:
    - name: udp-500
      protocol: UDP
      port: 500
      targetPort: 500
    - name: udp-4500
      protocol: UDP
      port: 4500
      targetPort: 4500
